name: Deploy to S3

on:
  push:
    branches: [developer]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2.1.2
    
    - name: Install and Build
      run: |
        npm install  
        npm run build  

    - name: Deploy to S3 Main
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: jakejarvis/s3-sync-action@master 
      # Trong phần Deploy to S3, jakejarvis/s3-sync-action@master là một GitHub Action được sử dụng để đồng bộ các tệp với một bucket S3.
      # Nó sử dụng các biến môi trường để truy cập vào tài khoản AWS của bạn và bucket S3.
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-northeast-1'  # Replace with your AWS region
        SOURCE_DIR: 'dist'  # Replace with your build directory
      

    - name: Deploy to S3 Staging
      if: ${{ github.ref == 'refs/heads/staging' }}
      uses: jakejarvis/s3-sync-action@staging
      # Trong phần Deploy to S3, jakejarvis/s3-sync-action@master là một GitHub Action được sử dụng để đồng bộ các tệp với một bucket S3.
      # Nó sử dụng các biến môi trường để truy cập vào tài khoản AWS của bạn và bucket S3.
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_STAGING }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-northeast-1'  # Replace with your AWS region
        SOURCE_DIR: 'dist'  # Replace with your build directory